<?php
/**
 * @var \Kirill\Coins\Block\CoinAttribute $block
 */
?>
<?php $data = explode(',',$block->getProduct()->getPrice()); ?>
<?php $status = $block->isEnabled() ?>
<?php $percent = 100/($block->getPercent()) ?>
<?php if($status == 1) :?>
    <ul class="product-icons">
        <h4>You Can Earn
            <?php foreach ($data as $value): ?>
                <?= (int)($value/$percent); ?>
            <?php endforeach; ?> Coins For Buying Product</h4>
    </ul>
<?php endif;?>
